config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :show] do
    resources :employees, only: [:show]
    resources :products, only: [:new, :show, :destroy]
    resources :sales, only: [:new, :show, :destroy]
  end

  resources :products, only: [:create, :update]
  resources :sales, only: [:create, :update]
  resources :sessions, only: [:new, :create]

  get '/login', :to => 'sessions#new'
  get '/logout', :to => 'sessions#destroy'
  get '/users', :to => 'welcome#welcome'
  get '/hot_products', :to => 'products#hot_products'
  get '/users/:user_id/manager', :to => 'managers#show', :as => 'manager'
  get '/auth/facebook/callback' => 'sessions#create'
  get '/sales/by_quantity' => 'sales#by_quantity'
  get '/sale_data/:id' => 'sales#data'
  get '/users/:id/sales' => 'users#sales'

  root 'welcome#welcome'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sales
  has_many :products, through: :sales
  has_many :manager_employees
  has_many :employees, through: :manager_employees

  validates_presence_of :name, :email, :password, on: :create
  validates_uniqueness_of :email, on: :create
  validates_acceptance_of :manager, :unless => :manager_id?
  validates_presence_of :manager_id, :unless => :manager?
  validate :manager_or_employee
  validate :valid_manager

  include ActionView::Helpers

  def is_manager?
    self.manager == true
  end

  def manager_products
    Product.where('manager_id = ?', self.id)
  end

  def revenue
    total = 0.0
    self.sales.each do |sale|
      total += sale.product.price * sale.quantity
    end
    if total % 1 == 0
      return "#{number_to_currency(total, precision: 0)}"
    else
      return "#{number_to_currency(total, precision: 2)}"
    end
  end

  def valid_manager
    if manager_id != nil && User.find(manager_id).manager == false
      errors.add(:manager_id, "There is no manager with that email address.")
    end
  end

  def manager_or_employee
    if manager == true && manager_id != nil
      errors.add(:manager, "Cannot be a manager and emplyee.")
    end
  end

  def total_earnings
    @total = 0
    self.sales.each do |sale|
      @total += sale.total.to_i * sale.product.commission
    end
    if @total % 1 == 0
      return @total.to_i
    else
      return '%.2f' % @total.round(2)
    end
  end

  def display_total_earnings
    if self.total_earnings % 1 == 0
      "#{number_to_currency(self.total_earnings, precision: 0)}"
    else
      "#{number_to_currency(self.total_earnings, precision: 2)}"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include UsersHelper

  before_action :require_login, only: [:show, :hot_products]
  before_action :set_form_variables, only: [:show, :hot_products]

  def create
    @user = User.new(name: params[:user][:name], email: params[:user][:email], password: params[:user][:password], manager: params[:user][:manager])
    @user.manager_id = set_manager_id
    if @user.save
      if !@user.is_manager?
        User.find(set_manager_id).employees << @user
      end
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'welcome/welcome'
    end
  end

  def show
    @user = User.find(params[:id])
    set_show_variables
    valid_page_view
    respond_to do |format|
      format.json { render json: @user, status: 200 }
      format.html { render :show }

    end
  end

  def sales
    @user = User.find(params[:id])
    @sales = @user.sales
    render json: @sales, satatus: 200
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def valid_page_view
    redirect_to user_path(current_user) unless is_current_users_profile? || is_current_users_employee? || is_employees_manager?
  end

  def set_show_variables
    if @user.is_manager?
      @employees = @user.employees
      @products = Product.where('manager_id = ?', @user.id).reverse_order
      @product = Product.new
    else
      @manager = User.find(@user.manager_id)
      @products = @user.products.uniq
      @sales = @user.sales.reverse_order
      @manager_products = Product.where('manager_id = ?', current_user.manager_id)
    end
  end

  def set_manager_id
    if params[:user][:manager_email] != ''
      if User.find_by(email: params[:user][:manager_email]) != nil
        return User.find_by(email: params[:user][:manager_email]).id
      else
        return nil
      end
    else
      return nil
    end
  end
end

app/views/users/_employee_show_body_left.html.erb
<div class="header_md_light_gray_skinny employee-body" data-id="<%= @user.id %>" id="user_name">
  <%= 'Hi, ' if is_current_users_profile? %><%= @user.name %>
</div>
<div class="header_xs_dark_blue_skinny" style="margin: 25px 0 10px 0" id="sales_header">
  Sales
</div>

app/views/users/_employee_show_body_right.html.erb
<div class="header_xs_dark_blue_skinny" style="margin-bottom: 10px">
  Earnings
</div>
<div class="full_width_white_box_container clearfix" style="text-align: center">
  <div class="earnings"><%= @user.display_total_earnings %></div>
</div>
<div class="header_xs_dark_blue_skinny" style="margin: 10px 0">
  Manager
</div>
<div class="full_width_white_box_container clearfix" style="text-align: center">
  <div class="people"><%= link_to @manager.name, manager_path(@user) %></div>
</div>
<div class="header_xs_dark_blue_skinny" style="margin: 10px 0">
  Products Sold
</div>
<% if @products.empty? %>
  <div class="full_width_white_box_container product_box clearfix" id="productsSoldEmpty" style="text-align: center">
    <div class="color_bar" style="background: #39474a"></div>
    <div class="empty">No products sold, yet.</div>
  </div>
<% else %>
  <% @products.each do |product| %>
    <div class="full_width_white_box_container product_box employee_product clearfix" id="employee-product-<%= product.id %>" data-product-id="<%= product.id %>">
      <div class="color_bar" style="background: <%= product.color %>"></div>
      <div class="contents">
        <span class="product-title"><%= product.title %></span>
        <div class="right display-number-sold"><%= display_number_sold(product.id) %></div>
        <div class="sub"><%= "Price: #{product.display_price}" %><%= " | #{product.commission_to_percent}% Commission" if !product.is_free? %></div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/users/_manager_show_body_left.html.erb
<div class="header_md_light_gray_skinny manager-body" data-id="<%= @user.id %>">
  <%= 'Hi, ' if is_current_users_profile? %><%= @user.name %>
</div>
<div class="header_xs_dark_blue_skinny" id="manager_products_header" style="margin: 25px 0 10px 0" data-id="<%= @user.id %>">
  Products
</div>

app/views/users/_manager_show_body_right.html.erb
<div class="header_xs_dark_blue_skinny" style="margin-bottom: 10px">
  Employees
  <div class="revenue">
    Revenue
  </div>
</div>
<div class="full_width_white_box_container clearfix" id="employee-container"></div>

app/views/users/show.html.erb
<div class="container clearfix">
  <div class="body_left">
    <% if @user.is_manager? %>
      <%= render 'users/manager_show_body_left' %>
    <% else %>
      <%= render 'users/employee_show_body_left' %>
    <% end %>
  </div>
  <div class="body_right">
    <% if @user.is_manager? %>
      <%= render 'users/manager_show_body_right' %>
      <% else %>
        <%= render 'users/employee_show_body_right' %>
      <% end %>
  </div>
</div>

<% if @user.is_manager? %>
  <script id="manager-product-template" type="text/x-handlebars-template">
    <div class="full_width_white_box_container product_box clearfix">
      <div class="color_bar" style="background: {{color}}"></div>
      <div class="contents">
        <% if current_user.id == @user.id %>
          <a href="/users/<%= @user.id %>/products/{{id}}">{{title}}</a>
        <% else %>
          {{title}}
        <% end %>
        <div class="right">{{price}}</div>
        {{# if isFree}}
          <div class="sub">{{saleCount}}</div>
        {{else}}
          <div class="sub">{{commission}} | {{saleCount}} Sales | {{revenue}} Total Revenue</div>
        {{/if}}
      </div>
    </div>
  </script>
  <script id="manager-empty-product-template" type="text/x-handlebars-template">
    <div class="full_width_white_box_container product_box clearfix" id="empty-manager-product-div">
      <div class="color_bar" style="background: #39474a"></div>
      <div class="empty" style="text-align: center">No products, yet.</div>
    </div>
  </script>
  <script id="manager-employee-template" type="text/x-handlebars-template">
      <div class="people clearfix"><a href="{{url}}">{{name}}</a><div class="revenue">{{revenue}}</div></div>
  </script>
  <script id="manager-empty-employee-template" type="text/x-handlebars-template">
    <div class="empty" style="text-align: center" id="empty-employee-div">No employees, yet.</div>
  </script>
<% else %>
  <script id="sale-template" type="text/x-handlebars-template">
    <div class="full_width_white_box_container product_box clearfix">
      <div class="color_bar" style="background: {{productColor}}"></div>
      <div class="contents">
        <% if current_user.id == @user.id %>
          <a href="/users/<%= @user.id %>/sales/{{id}}">{{productTitle}}</a>
        <% else %>
          {{productTitle}}
        <% end %>
        <div class="right">{{earnings}}</div>
        <div class="sub">
          {{#if isFree}}
            FREE | Quantity: {{quantity}}
          {{else}}
            Total: {{total}} | {{commission}} | Quantity: {{quantity}}
          {{/if}}
        </div>
      </div>
    </div>
  </script>
  <script id="empty-sale-template" type="text/x-handlebars-template">
    <div class="full_width_white_box_container product_box clearfix" id="empty-sale-div" style="text-align: center">
      <div class="color_bar" style="background: #39474a"></div>
      <div class="empty">No sales, yet.</div>
    </div>
  </script>
  <script id="employee-product-template" type="text/x-handlebars-template">
    <div class="full_width_white_box_container product_box employee_product clearfix" id="employee-product-{{id}}" data-product-id="{{id}}">
      <div class="color_bar" style="background: {{color}}"></div>
      <div class="contents">
        <span class="product-title">{{title}}</span>
        <div class="right display-number-sold">{{numberSold}} Sold</div>
        <div class="sub">
          {{#if isFree}}
            FREE
          {{else}}
            Price: {{price}} | {{commission}}
          {{/if}}
        </div>
      </div>
    </div>
  </script>
  <script id="empty-employee-product-template" type="text/x-handlebars-template">
    <div class="full_width_white_box_container product_box clearfix" id="productsSoldEmpty" style="text-align: center">
      <div class="color_bar" style="background: #39474a"></div>
      <div class="empty">No products sold, yet.</div>
    </div>
  </script>
<% end %>