config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :show] do
    resources :employees, only: [:show]
    resources :products, only: [:new, :show, :destroy]
    resources :sales, only: [:new, :show, :destroy]
  end

  resources :products, only: [:create, :update]
  resources :sales, only: [:create, :update]
  resources :sessions, only: [:new, :create]

  get '/login', :to => 'sessions#new'
  get '/logout', :to => 'sessions#destroy'
  get '/users', :to => 'welcome#welcome'
  get '/hot_products', :to => 'products#hot_products'
  get '/users/:user_id/manager', :to => 'managers#show', :as => 'manager'
  get '/auth/facebook/callback' => 'sessions#create'
  get '/sales/by_quantity' => 'sales#by_quantity'
  get '/sale_data/:id' => 'sales#data'
  get '/users/:id/sales' => 'users#sales'

  root 'welcome#welcome'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :sales
  has_many :users, through: :sales

  validates_presence_of :title, :price, :commission, :color
  validates :price, numericality: true

  include ActionView::Helpers

  def self.list_hot_products(user_id)
    self.joins(:sales).group('products.id').where('products.manager_id = ?', user_id).order('count(sales.id) DESC').limit(3).select('products.*')
  end

  def commission_to_percent
    "#{(self.commission * 100).to_i}"
  end

  def revenue
    total = 0.0
    self.sales.each do |sale|
      total += sale.product.price * sale.quantity
    end
    if total % 1 == 0
      return "#{number_to_currency(total, precision: 0)}"
    else
      return "#{number_to_currency(total, precision: 2)}"
    end
  end

  def formatted_price
    if self.price % 1 == 0
      return self.price.to_i
    else
      return '%.2f' % self.price.round(2)
    end
  end

  def display_price
    if self.is_free?
      return "Free"
    else
      if self.formatted_price % 1 == 0
        "#{number_to_currency(self.formatted_price, precision: 0)}"
      else
        "#{number_to_currency(self.formatted_price, precision: 2)}"
      end
    end
  end

  def is_free?
    self.price == 0
  end

  def sale_count
    pluralize(self.sales.count, 'Sale')
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :require_login, only: [:show, :new, :create, :update]

  include ProductsHelper

  def new
    redirect_to user_path(current_user) unless current_user.is_manager?
    @js = ['products_form']
    @product = Product.new
  end

  def create
    redirect_to user_path(current_user) unless current_user.is_manager?
    @product = Product.new
    @product.title = params[:product][:title]
    @product.price = set_price
    @product.commission = set_commission
    @product.color = params[:product][:color]
    @product.manager_id = current_user.id
    if @product.save
      render json: @product, status: 201
    else
      render json: { errors: @product.errors }
    end
  end

  def show
    redirect_to user_path(current_user) unless current_user.manager_products.include?(Product.find(params[:id])) && current_user.is_manager?
    @js = ['products_form']
    @user = User.find(params[:user_id])
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.title = params[:product][:title]
    @product.price = set_price
    @product.commission = set_commission
    @product.color = params[:product][:color]
    if @product.save
      redirect_to user_path(current_user)
    else
      @js = ['products_form']
      @user = User.find(params[:user_id])
      render 'show'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if current_user.id == params[:user_id].to_i
      Sale.where('product_id = ?', @product.id).destroy_all
      @product.destroy
      redirect_to user_path(current_user)
    else
      redirect_to user_path(current_user)
    end
  end

  def hot_products
    if current_user.is_manager?
      @user = current_user
      @products = Product.list_hot_products(current_user.id)

      respond_to do |format|
        format.json { render json: @products, status: 200 }
        format.html { render :hot_products }
      end
    else
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper

  def set_price
    params[:product][:price] != '' ? params[:product][:price].to_f : nil
  end

  def set_commission
    params[:product][:commission] != '' ? params[:product][:commission].to_f / 100 : nil
  end

end

app/views/products/_edit_form.html.erb
<%= form_for(@product) do |f| %>
  <div class="form_box_md">
    <div class="<%= "field_with_errors" if @product.errors.include?(:title) %>">
      <%= f.label :title %>
    </div>
    <%= f.text_field :title, class: 'form_box_md_input_text' %>
    <div class="<%= "field_with_errors" if @product.errors.include?(:price) %>">
      <%= f.label :price %>
    </div>
    <%= f.text_field :price, value: @product.formatted_price, class: 'form_box_md_input_text' %>
    <div class="<%= "field_with_errors" if @product.errors.include?(:commission) %>">
      <%= f.label :commission, 'Commission (percent)' %>
    </div>
    <%= f.text_field :commission, value: @product.commission_to_percent, class: 'form_box_md_input_text' %>
    <div class="<%= "field_with_errors" if @product.errors.include?(:color) %>">
      <%= f.label :color %>
    </div>
    <div>
      <div class="color_box" style=" background: #E53935"></div>
      <div class="color_box" style=" background: #F57C00"></div>
      <div class="color_box" style=" background: #FFEB3B"></div>
      <div class="color_box" style=" background: #4CAF50"></div>
      <div class="color_box" style=" background: #039BE5"></div>
      <div class="color_box" style=" background: #5E35B1"></div>
    </div>
    <%= f.text_field :color, class: 'form_box_md_input_text' %>
  </div>
  <%= f.submit 'Update', class: 'form_full_btn' %>
  <%= link_to user_product_path(current_user, @product), method: :delete do %>
    <div class="form_full_delete_btn">
      Delete
    </div>
  <% end %>
<% end %>

app/views/products/_new_form.html.erb
<%= form_for(@product) do |f| %>
  <div class="form_box_md">
    <div class="<%= "field_with_errors" if @product.errors.include?(:title) %>">
      <%= f.label :title %>
    </div>
    <%= f.text_field :title, class: 'form_box_md_input_text' %>
    <div class="<%= "field_with_errors" if @product.errors.include?(:price) %>">
      <%= f.label :price %>
    </div>
    <%= f.text_field :price, class: 'form_box_md_input_text' %>
    <div class="<%= "field_with_errors" if @product.errors.include?(:commission) %>">
      <%= f.label :commission, 'Commission (percent)' %>
    </div>
    <%= f.text_field :commission, class: 'form_box_md_input_text' %>
    <div class="<%= "field_with_errors" if @product.errors.include?(:color) %>">
      <%= f.label :color %>
    </div>
    <div>
      <div class="color_box" style=" background: #E53935"></div>
      <div class="color_box" style=" background: #F57C00"></div>
      <div class="color_box" style=" background: #FFEB3B"></div>
      <div class="color_box" style=" background: #4CAF50"></div>
      <div class="color_box" style=" background: #039BE5"></div>
      <div class="color_box" style=" background: #5E35B1"></div>
    </div>
    <%= f.text_field :color, class: 'form_box_md_input_text' %>
  </div>
  <%= f.submit 'Add Product', class: 'form_full_btn' %>
<% end %>

app/views/products/hot_products.html.erb
<div class="container" id="hot_products_container" data-id="<%= @user.id %>">
  <div class="header_xs_dark_blue_skinny" style="margin: 25px 0 10px 0">
    Hot Products
  </div>
</div>

<script id="manager-product-template" type="text/x-handlebars-template">
  <div class="full_width_white_box_container product_box clearfix">
    <div class="color_bar" style="background: {{color}}"></div>
    <div class="contents">
      <% if current_user.id == @user.id %>
        <a href="/users/<%= @user.id %>/products/{{id}}">{{title}}</a>
      <% else %>
        {{title}}
      <% end %>
      <div class="right">{{price}}</div>
      {{# if isFree}}
        <div class="sub">{{saleCount}}</div>
      {{else}}
        <div class="sub">{{commission}} | {{saleCount}} Sales | {{revenue}} Total Revenue</div>
      {{/if}}
    </div>
  </div>
</script>
<script id="manager-hot-product-empty-template" type="text/x-handlebars-template">
  <div class="full_width_white_box_container product_box clearfix" style="text-align: center">
    <div class="color_bar" style="background: #39474a"></div>
    <div class="empty">No hot products.</div>
  </div>
</script>