config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :show] do
    resources :employees, only: [:show]
    resources :products, only: [:new, :show, :destroy]
    resources :sales, only: [:new, :show, :destroy]
  end

  resources :products, only: [:create, :update]
  resources :sales, only: [:create, :update]
  resources :sessions, only: [:new, :create]

  get '/login', :to => 'sessions#new'
  get '/logout', :to => 'sessions#destroy'
  get '/users', :to => 'welcome#welcome'
  get '/hot_products', :to => 'products#hot_products'
  get '/users/:user_id/manager', :to => 'managers#show', :as => 'manager'
  get '/auth/facebook/callback' => 'sessions#create'
  get '/sales/by_quantity' => 'sales#by_quantity'
  get '/sale_data/:id' => 'sales#data'
  get '/users/:id/sales' => 'users#sales'

  root 'welcome#welcome'
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates_presence_of :product_id, :quantity

  include ActionView::Helpers

  def total
    total_a = self.product.price * self.quantity
    if total_a % 1 == 0
      return total_a.to_i
    else
      return '%.2f' % total_a.round(2)
    end
  end

  def display_total
    if self.total % 1 == 0
      "#{number_to_currency(self.total, precision: 0)}"
    else
      "#{number_to_currency(self.total, precision: 2)}"
    end
  end

  def earnings
    total_a = self.total.to_i * self.product.commission
    if total_a % 1 == 0
      return total_a.to_i
    else
      return '%.2f' % total_a.round(2)
    end
  end

  def display_earnings
    if self.earnings % 1 == 0
      "#{number_to_currency(self.earnings, precision: 0)}"
    else
      "#{number_to_currency(self.earnings, precision: 2)}"
    end
  end

  def self.display_by_quantity
    order(quantity: :desc)
  end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  before_action :require_login, only: [:show, :new, :create, :update]

  def new
    redirect_to user_path(current_user) unless !current_user.is_manager?
    @sale = Sale.new
    @manager_products = Product.where('manager_id = ?', current_user.manager_id)
  end

  def create
    redirect_to user_path(current_user) unless !current_user.is_manager?
    @sale = Sale.new
    @sale.quantity = params[:sale][:quantity]
    @sale.product_id = params[:sale][:product_id]
    @sale.user_id = current_user.id
    if @sale.save
      render json: @sale, status: 201
    else
      render json: { errors: @sale.errors }
    end
  end

  def show
    redirect_to user_path(current_user) unless current_user.sales.include?(Sale.find(params[:id])) && !current_user.is_manager?
    @user = User.find(params[:user_id])
    @sale = Sale.find(params[:id])
    @manager_products = Product.where('manager_id = ?', current_user.manager_id)
  end

  def data
    if current_user.sales.include?(Sale.find(params[:id])) && !current_user.is_manager?
      @sale = Sale.find(params[:id])
      render json: @sale, status: 200
    end
  end

  def update
    @sale = Sale.find(params[:id])
    @sale.product_id = params[:sale][:product_id]
    @sale.quantity = params[:sale][:quantity]
    if @sale.save
      redirect_to user_path(current_user)
    else
      @user = User.find(params[:user_id])
      render 'show'
    end
  end

  def destroy
    @sale = Sale.find(params[:id])
    if current_user.id == params[:user_id].to_i
      @sale.destroy
      redirect_to user_path(current_user)
    else
      redirect_to user_path(current_user)
    end
  end

  def by_quantity
    @sales = Sale.display_by_quantity
  end

end

app/views/sales/_edit_form.html.erb
<%= form_for(@sale) do |f| %>
  <div class="form_box_md">
    <div class="<%= "field_with_errors" if @sale.errors.include?(:quantity) %>">
      <%= f.label :product_id, 'Product' %>
    </div>
    <%= f.select(:product_id, @manager_products.collect {|p| [ p.title, p.id ] }, { include_blank: true }) %>
    <div class="<%= "field_with_errors" if @sale.errors.include?(:quantity) %>">
      <%= f.label :quantity %>
    </div>
    <%= f.text_field :quantity, class: 'form_box_md_input_text' %>
  </div>
  <%= f.submit 'Update Sale', class: 'form_full_btn' %>
  <%= link_to user_sale_path(current_user, @sale), method: :delete do %>
    <div class="form_full_delete_btn">
      Delete
    </div>
  <% end %>
<% end %>

app/views/sales/_new_form.html.erb
<%= form_for(@sale) do |f| %>
  <div class="form_box_md">
    <div class="<%= "field_with_errors" if @sale.errors.include?(:quantity) %>">
      <%= f.label :product_id, 'Product' %>
    </div>
    <%= f.select(:product_id, @manager_products.collect {|p| [ p.title, p.id ] }, { include_blank: true }) %>
    <div class="<%= "field_with_errors" if @sale.errors.include?(:quantity) %>">
      <%= f.label :quantity %>
    </div>
    <%= f.text_field :quantity, class: 'form_box_md_input_text' %>
  </div>
  <%= f.submit 'Add Sale', class: 'form_full_btn' %>
<% end %>

app/views/sales/by_quantity.html.erb
<ul>
  <% @sales.each do |sale| %>
    <li>
      <%= sale.product.title %>, <%= sale.quantity %>
    </li>
  <% end %>
</ul>

app/views/sales/new.html.erb
<div class="container">
  <div class="form_box_md_container">
    <%= render 'new_form' %>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
  $(function () {
    $('form').submit(function(event) {
      //prevent form from submitting the default way
      event.preventDefault();

      var values = $(this).serialize();

      var posting = $.post('/sales', values);

      posting.done(function(data) {
        console.log(data);
      });
    });
  });
</script>

app/views/sales/show.html.erb
<div class="container">
  <div class="form_box_md_container">
    <%= render 'edit_form' %>
  </div>
</div>