config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :show] do
    resources :employees, only: [:show]
    resources :products, only: [:new, :show, :destroy]
    resources :sales, only: [:new, :show, :destroy]
  end

  resources :products, only: [:create, :update]
  resources :sales, only: [:create, :update]
  resources :sessions, only: [:new, :create]

  get '/login', :to => 'sessions#new'
  get '/logout', :to => 'sessions#destroy'
  get '/users', :to => 'welcome#welcome'
  get '/hot_products', :to => 'products#hot_products'
  get '/users/:user_id/manager', :to => 'managers#show', :as => 'manager'
  get '/auth/facebook/callback' => 'sessions#create'
  get '/sales/by_quantity' => 'sales#by_quantity'
  get '/sale_data/:id' => 'sales#data'
  get '/users/:id/sales' => 'users#sales'

  root 'welcome#welcome'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommissionTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <div class="container">
        <div class="logo">
          <% if logged_in? %>
            <%= link_to 'Commission Tracker', user_path(current_user) %>
          <% else %>
            <%= link_to 'Commission Tracker', root_path %>
          <% end %>
        </div>
        <% if logged_in? %>
          <% if current_user_is_manager? && is_current_users_profile? %>
            <div class="button">
              New Product
            </div>
            <div class="form_box_md_container_popup">
              <div class="form_box_popup form_box_md" style="border: 0">
                <%= form_for(@product) do |f| %>
                  <div id="product-title-label">
                    <%= f.label :title %>
                  </div>
                  <%= f.text_field :title, class: 'form_box_md_input_text' %>
                  <div id="product-price-label">
                    <%= f.label :price %>
                  </div>
                  <%= f.text_field :price, class: 'form_box_md_input_text' %>
                  <div id="product-commission-label">
                    <%= f.label :commission, 'Commission (percent)' %>
                  </div>
                  <%= f.text_field :commission, class: 'form_box_md_input_text' %>
                  <div id="product-color-label">
                    <%= f.label :color %>
                  </div>
                  <div>
                    <div class="color_box" style=" background: #E53935"></div>
                    <div class="color_box" style=" background: #F57C00"></div>
                    <div class="color_box" style=" background: #FFEB3B"></div>
                    <div class="color_box" style=" background: #4CAF50"></div>
                    <div class="color_box" style=" background: #039BE5"></div>
                    <div class="color_box" style=" background: #5E35B1"></div>
                  </div>
                  <%= f.text_field :color, class: 'form_box_md_input_text' %>
                  <%= f.submit 'Add Product', class: 'form_full_btn', data: { disable_with: false }  %>
                <% end %>
              </div>
            </div>
          <% elsif is_current_users_profile? %>
            <div class="button">
              New Sale
            </div>
            <div class="form_box_md_container_popup">
              <div class="form_box_popup form_box_md">
                <%= form_for(@sale) do |f| %>
                  <div id="sale-product-label">
                    <%= f.label :product_id, 'Product' %>
                  </div>
                  <%= f.select(:product_id, @manager_products.collect {|p| [ p.title, p.id ] }, { include_blank: true }) %>
                  <div id="sale-quantity-label">
                    <%= f.label :quantity %>
                  </div>
                  <%= f.text_field :quantity, class: 'form_box_md_input_text' %>
                  <%= f.submit 'Add Sale', class: 'form_full_btn', data: { disable_with: false } %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
        <div class="logout">
          <% if logged_in? %>
            <%= link_to 'Logout', logout_path %>
          <% else %>
            <%= link_to 'Login', login_path %>
          <% end %>
        </div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>